### ISSUE TITLE
Should use "id" for inline schema instead of "name"

### ISSUE THREAD

**Issue by atlithorn** [gangverk/flask-swagger#1]
As per JSON Schema

```
schema:
  id: "#/definitions/Bla"
  properties:
    bla:
      type: string
      description: Bla
```
